// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatPozoriste.Data;

#nullable disable

namespace ProjekatPozoriste.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617083455_FixZaposleniPredstavaRelation")]
    partial class FixZaposleniPredstavaRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PredstavaZaposleni", b =>
                {
                    b.Property<int>("PredstaveId")
                        .HasColumnType("int");

                    b.Property<int>("UcesniciId")
                        .HasColumnType("int");

                    b.HasKey("PredstaveId", "UcesniciId");

                    b.HasIndex("UcesniciId");

                    b.ToTable("PredstavaZaposleni");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Karta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojSjedista")
                        .HasColumnType("int");

                    b.Property<double>("Cijena")
                        .HasColumnType("double");

                    b.Property<int>("Stanje")
                        .HasColumnType("int");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminId");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Pozoriste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pozorista");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PozoristeId")
                        .HasColumnType("int");

                    b.Property<string>("PutanjaSlike")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PozoristeId");

                    b.ToTable("Predstave");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.ProdajaKarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImeKupca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KartaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdavacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KartaId");

                    b.HasIndex("ProdavacId");

                    b.ToTable("ProdajaKarata");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PredstavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredstavaId");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Zaposleni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PozoristeId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozoristeId");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("PredstavaZaposleni", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Predstava", null)
                        .WithMany()
                        .HasForeignKey("PredstaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjekatPozoriste.Models.Zaposleni", null)
                        .WithMany()
                        .HasForeignKey("UcesniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Karta", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Termin", "Termin")
                        .WithMany("Karte")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Pozoriste", "Pozoriste")
                        .WithMany("Predstave")
                        .HasForeignKey("PozoristeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozoriste");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.ProdajaKarte", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Karta", "Karta")
                        .WithMany()
                        .HasForeignKey("KartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjekatPozoriste.Models.Zaposleni", "Prodavac")
                        .WithMany()
                        .HasForeignKey("ProdavacId");

                    b.Navigation("Karta");

                    b.Navigation("Prodavac");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Termin", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Predstava", "Predstava")
                        .WithMany("Termini")
                        .HasForeignKey("PredstavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predstava");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Zaposleni", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Pozoriste", "Pozoriste")
                        .WithMany("Zaposleni")
                        .HasForeignKey("PozoristeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozoriste");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Pozoriste", b =>
                {
                    b.Navigation("Predstave");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Termin", b =>
                {
                    b.Navigation("Karte");
                });
#pragma warning restore 612, 618
        }
    }
}
