// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatPozoriste.Data;

#nullable disable

namespace ProjekatPozoriste.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjekatPozoriste.Models.Karta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojSedista")
                        .HasColumnType("int");

                    b.Property<bool>("IsProdata")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PredstavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredstavaId");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Pozoriste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pozorista");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PozoristeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozoristeId");

                    b.ToTable("Predstave");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Zaposleni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PozoristeId")
                        .HasColumnType("int");

                    b.Property<int?>("PredstavaId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozoristeId");

                    b.HasIndex("PredstavaId");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Karta", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Predstava", "Predstava")
                        .WithMany()
                        .HasForeignKey("PredstavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predstava");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Pozoriste", "Pozoriste")
                        .WithMany("Predstave")
                        .HasForeignKey("PozoristeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozoriste");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Zaposleni", b =>
                {
                    b.HasOne("ProjekatPozoriste.Models.Pozoriste", "Pozoriste")
                        .WithMany("Zaposleni")
                        .HasForeignKey("PozoristeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjekatPozoriste.Models.Predstava", null)
                        .WithMany("Ucesnici")
                        .HasForeignKey("PredstavaId");

                    b.Navigation("Pozoriste");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Pozoriste", b =>
                {
                    b.Navigation("Predstave");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("ProjekatPozoriste.Models.Predstava", b =>
                {
                    b.Navigation("Ucesnici");
                });
#pragma warning restore 612, 618
        }
    }
}
